language: python
python:
  - '2.7'
notifications:
  email: false
  slack:
    secure: GTVOuQvLJwVkIDsoAq7peVMdj27dtbTw7aVJ6n/Go09BVS8kCCrLfV+dxcH990JP/rtXqs0w++MmF9NxKm28wF+MdHAiHCOJxR4mcwsy9NuO+KoYysfmbmUVzZydgoys0jD+nS2zlwHq4C+/+a7Let7+5YOdt56sVLFS2Ll6G+E=
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo pip install conda
  - conda init
  - conda update conda --yes
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda create -n build --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose cython pip scikit-learn
  - source activate build
  - conda install --yes -c distributions distributions
  - conda install --yes -c datamicroscopes eigen3
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - printenv
  - conda list --export
  - mkdir .travis
  - (cd .travis && git clone https://github.com/datamicroscopes/common.git && cd common && make travis_install)
  - (cd .travis && git clone https://github.com/datamicroscopes/kernels.git && cd kernels && make travis_install)
install: make travis_install
script: make travis_script
