package:
  name: microscopes-lda
  version: "0.2.2"

source:
  git_url: https://github.com/datamicroscopes/lda.git

requirements:
  build:
    - cmake
    - python
    - numpy ==1.8.2
    - cython >=0.20.2
    - distributions >=2.0.23
    - nose
    - eigen3
    - microscopes-common
  run:
    - python
    - numpy ==1.8.2
    - scipy
    - distributions >=2.0.23
    - nose
    - microscopes-common

test:
  imports:
    - microscopes.lda
    - microscopes.lda.definition
    - microscopes.lda.model

about:
  home: https://github.com/datamicroscopes/lda
